### PR TITLE
Convert docs to Markdown & add contribution instructions.

### PR DESCRIPTION
**Pull request by amfarrell**
As noted in issue #136, the documentation is incomplete.
By converting to a more user-friendly syntax and adding instructions
for how to contribute to the documentation, this will bring
django-user-accounts closer to having a better developer experience for
new users.

### CODE REVIEW

**Comment by amfarrell** [comment]
There are some deficiencies in the CSS styling of this. In of particular note, the two tables need borders. I wanted to see how receptive y'all were to something like this before moving forward on that though.

**Comment by luzfcb** [comment]
@amfarrell one question: this is still compatible with readthedocs.org?

**Comment by paltman** [comment]
Yes. In fact, we have already begun the migration of all of Pinax by converting other Pinax apps.

**Comment by ossanna16** [comment]
@paltman @brosner Can this pull request be merged (there seems to be a conflict) or closed? Or does it have to be modified?

**Pull request closed without merging**
