### PR TITLE
Check the email against the email address, not the code

### PR DESCRIPTION
**Pull request by larubbio**
When checking if a signup code exists the existing code was comparing the email address against the code

### CODE REVIEW

**Comment by jtauber** [comment]
We should write a regression test for this (although needn't block merging)

**Comment by larubbio** [comment]
Just an FYI, I'm working on adding REST apis for this module with django rest framework.  I'm not sure if you want that submitted as a PR.  I do have tests for this there and that is how I found the issue.

**Comment by larubbio** [comment]
I've added tests for the SignupCode exists method.

**Comment by ossanna16** [comment]
@larubbio Thank you for adding the tests! @jtauber Can this be merged?

**Comment by jtauber** [comment]
I'd like @brosner to approve and do the merge.

**Comment by ossanna16** [comment]
👍

**Comment by brosner** [comment]
Can the tests be updated to reflect the Pinax coding style guide? Thanks!

**Comment by larubbio** [comment]
If someone else has the time to update them feel free.  I'm not actually using this package anymore and don't have time to research the pinax style guide and update the tests.

**Review by paltman — APPROVED** [review]

**Pull request merged**
