### PR TITLE
Fix up tests

### PR DESCRIPTION
**Pull request by paltman**

### CODE REVIEW

**Comment by brosner** [comment]
I don't think we should remove testing against the development version of Django.

**Comment by paltman** [comment]
Fair enough. I can add back in `master`, which I know will break.  But then we can make it work and turn back to fixed.

**Comment by paltman** [comment]
As is, though, the tests are not testing against 1.9.

**Comment by brosner** [comment]
Right. I guess that's because Django branched off 1.9 and master is now 1.10.

**Pull request merged**
