### PR TITLE
Add support for html email templates

### PR DESCRIPTION
**Pull request by longchiwen**
Current implementation can only load `txt` based email templates. This commit adds support to optionally load `html` based email templates too. 

The work is based on #262 by @jr-hypertext. It will gracefully fallback to old behavior if `html` template does not exist.

### CODE REVIEW

**Comment by bluedisk** [comment]
It should be merged! I need this feature! Plz!
I think those codes are clean with beautiful test code!

**Comment by longchiwen** [comment]
@bluedisk, feel free to use my fork that has this feature implemented. See https://github.com/longchiwen/django-user-accounts

**Comment by KatherineMichel** [comment]
Typically, @brosner or @paltman merge PRs here. Hopefully one of them will be able to take a look soon. @bluedisk For situations like this, if there is not a fork, you can fetch the PR branch locally and merge or use standalone.

**Comment by paltman** [comment]
You can send HTML messages with DUA by providing your own hookset in your project and overriding `ACCOUNT_HOOKSET` setting to point to it.  This has been done on a number of project I've worked on personally and was the reason for adding the hookset form of extensibility. 

For example, add a `hooks.py` to your project:

```python
from django.conf import settings
from django.core.mail import EmailMultiAlternatives
from django.template.loader import render_to_string

from account.hooks import AccountDefaultHookSet


class CustomAccountHookSet(AccountDefaultHookSet):

    def send_invitation_email(self, to, ctx):
        subject = render_to_string("account/email/invite_user_subject.txt", ctx).strip()
        message = render_to_string("account/email/invite_user.txt", ctx)
        html = render_to_string("account/email/invite_user.html", ctx)
        msg = EmailMultiAlternatives(subject, message, settings.DEFAULT_FROM_EMAIL, to)
        msg.attach_alternative(html, "text/html")
        msg.send()
```

Then in your settings.py:

```
ACCOUNT_HOOKSET = "myproject.hooks.CustomHookSet"
```

**Comment by longchiwen** [comment]
Thanks for the explanation. I was not aware of the hooks. Like the approach 👍

**Pull request closed without merging**
