### PR TITLE
Ready version 3.3

### PR DESCRIPTION
**Pull request by blag**
Changes proposed in this PR:

- Exclude more files from our built distribution (eg: `tests/`, `tox.ini`, `docs/Makefile`, `docs/conf.py`)
- Simplify `pyproject.toml` a bit regarding what files to include
- Bump version to 3.3.0 for release

I verified that the built distribution only contains the appropriate files

<details>
<summary>Click here to see distribution file list</summary>

```
❯ tree dist/django-user-accounts-3.3.0
dist/django-user-accounts-3.3.0
├── CHANGELOG.md
├── LICENSE
├── MANIFEST.in
├── PKG-INFO
├── README.md
├── account
│   ├── __init__.py
│   ├── admin.py
│   ├── auth_backends.py
│   ├── conf.py
│   ├── context_processors.py
│   ├── decorators.py
│   ├── fields.py
│   ├── forms.py
│   ├── hooks.py
│   ├── languages.py
│   ├── locale
│   │   ├── ar
│   │   │   └── LC_MESSAGES
│   │   │       ├── django.mo
│   │   │       └── django.po
│   │   ├── de
│   │   │   └── LC_MESSAGES
│   │   │       ├── django.mo
│   │   │       └── django.po
│   │   ├── es
│   │   │   └── LC_MESSAGES
│   │   │       ├── django.mo
│   │   │       └── django.po
│   │   ├── fa_IR
│   │   │   └── LC_MESSAGES
│   │   │       ├── django.mo
│   │   │       └── django.po
│   │   ├── fr
│   │   │   └── LC_MESSAGES
│   │   │       ├── django.mo
│   │   │       └── django.po
│   │   ├── it
│   │   │   └── LC_MESSAGES
│   │   │       ├── django.mo
│   │   │       └── django.po
│   │   ├── ja
│   │   │   └── LC_MESSAGES
│   │   │       ├── django.mo
│   │   │       └── django.po
│   │   ├── nl
│   │   │   └── LC_MESSAGES
│   │   │       ├── django.mo
│   │   │       └── django.po
│   │   ├── pl
│   │   │   └── LC_MESSAGES
│   │   │       ├── django.mo
│   │   │       └── django.po
│   │   ├── pt_BR
│   │   │   └── LC_MESSAGES
│   │   │       ├── django.mo
│   │   │       └── django.po
│   │   ├── ru
│   │   │   └── LC_MESSAGES
│   │   │       ├── django.mo
│   │   │       └── django.po
│   │   ├── sk_SK
│   │   │   └── LC_MESSAGES
│   │   │       ├── django.mo
│   │   │       └── django.po
│   │   ├── tr
│   │   │   └── LC_MESSAGES
│   │   │       ├── django.mo
│   │   │       └── django.po
│   │   ├── zh_CN
│   │   │   └── LC_MESSAGES
│   │   │       ├── django.mo
│   │   │       └── django.po
│   │   └── zh_TW
│   │       └── LC_MESSAGES
│   │           ├── django.mo
│   │           └── django.po
│   ├── managers.py
│   ├── middleware.py
│   ├── mixins.py
│   ├── models.py
│   ├── signals.py
│   ├── timezones.py
│   ├── urls.py
│   ├── utils.py
│   └── views.py
├── django_user_accounts.egg-info
│   ├── PKG-INFO
│   ├── SOURCES.txt
│   ├── dependency_links.txt
│   ├── requires.txt
│   └── top_level.txt
├── docs
│   ├── commands.rst
│   ├── faq.rst
│   ├── index.rst
│   ├── installation.rst
│   ├── migration.rst
│   ├── settings.rst
│   ├── signals.rst
│   ├── templates.rst
│   └── usage.rst
├── pyproject.toml
└── setup.cfg

35 directories, 70 files
```

</summary>

**Tips for an ideal PR**
* You have read our Code of Conduct: https://github.com/pinax/.github/blob/master/CODE_OF_CONDUCT.md
* You have read our Contributing info: https://github.com/pinax/.github/blob/master/CONTRIBUTING.md
* The PR is atomic
* Unit tests have been updated/added, if needed
* App version number has been updated in `setup.py` (Pinax uses [SemVer](https://semver.org/))
* `Change Log` has been updated
* You have added your name to the `AUTHORS` file

### CODE REVIEW

**Review by uhurusurfa — APPROVED** [review]
👍 Looks good

**Comment by blag** [comment]
Sweet, thanks for the merge. I'll see if I can publish this new version to PyPI.

**Comment by VichoReyes** [comment]
Aren't migration files missing?

**Comment by blag** [comment]
Thank you for catching this. Yes, it's now missing migrations.

If I had a nickel for every time I messed up setuptools packaging config, I'd be unfathomably rich.

Fix and version bump PR incoming. Also looking into yanking the broken package from PyPI.

**Comment by blag** [comment]
I don't have permission to yank the package from PyPI.

Fix PR is #373.

**Pull request merged**
