### PR TITLE
Include migrations and bump version to 3.3.1

### PR DESCRIPTION
**Pull request by blag**
Changes proposed in this PR:

- Bump version to 3.3.1
- Explicitly `recursive-include` migrations files in `MANIFEST.in`

**Tips for an ideal PR**
* You have read our Code of Conduct: https://github.com/pinax/.github/blob/master/CODE_OF_CONDUCT.md
* You have read our Contributing info: https://github.com/pinax/.github/blob/master/CONTRIBUTING.md
* The PR is atomic
* Unit tests have been updated/added, if needed
* App version number has been updated in `setup.py` (Pinax uses [SemVer](https://semver.org/))
* `Change Log` has been updated
* You have added your name to the `AUTHORS` file

### CODE REVIEW

**Comment by blag** [comment]
Don't merge this just yet

**Comment by blag** [comment]
That was a slog.

This PR should be ready.

<details>
<summary>
Contents of wheel
</summary>

```
❯ tree dist/django_user_accounts-3.3.1-py3-none-any
dist/django_user_accounts-3.3.1-py3-none-any
├── account
│   ├── __init__.py
│   ├── admin.py
│   ├── auth_backends.py
│   ├── conf.py
│   ├── context_processors.py
│   ├── decorators.py
│   ├── fields.py
│   ├── forms.py
│   ├── hooks.py
│   ├── languages.py
│   ├── locale
│   │   ├── ar
│   │   │   └── LC_MESSAGES
│   │   │       ├── django.mo
│   │   │       └── django.po
│   │   ├── de
│   │   │   └── LC_MESSAGES
│   │   │       ├── django.mo
│   │   │       └── django.po
│   │   ├── es
│   │   │   └── LC_MESSAGES
│   │   │       ├── django.mo
│   │   │       └── django.po
│   │   ├── fa_IR
│   │   │   └── LC_MESSAGES
│   │   │       ├── django.mo
│   │   │       └── django.po
│   │   ├── fr
│   │   │   └── LC_MESSAGES
│   │   │       ├── django.mo
│   │   │       └── django.po
│   │   ├── it
│   │   │   └── LC_MESSAGES
│   │   │       ├── django.mo
│   │   │       └── django.po
│   │   ├── ja
│   │   │   └── LC_MESSAGES
│   │   │       ├── django.mo
│   │   │       └── django.po
│   │   ├── nl
│   │   │   └── LC_MESSAGES
│   │   │       ├── django.mo
│   │   │       └── django.po
│   │   ├── pl
│   │   │   └── LC_MESSAGES
│   │   │       ├── django.mo
│   │   │       └── django.po
│   │   ├── pt_BR
│   │   │   └── LC_MESSAGES
│   │   │       ├── django.mo
│   │   │       └── django.po
│   │   ├── ru
│   │   │   └── LC_MESSAGES
│   │   │       ├── django.mo
│   │   │       └── django.po
│   │   ├── sk_SK
│   │   │   └── LC_MESSAGES
│   │   │       ├── django.mo
│   │   │       └── django.po
│   │   ├── tr
│   │   │   └── LC_MESSAGES
│   │   │       ├── django.mo
│   │   │       └── django.po
│   │   ├── zh_CN
│   │   │   └── LC_MESSAGES
│   │   │       ├── django.mo
│   │   │       └── django.po
│   │   └── zh_TW
│   │       └── LC_MESSAGES
│   │           ├── django.mo
│   │           └── django.po
│   ├── management
│   │   ├── __init__.py
│   │   └── commands
│   │       ├── __init__.py
│   │       ├── expunge_deleted.py
│   │       ├── user_password_expiry.py
│   │       └── user_password_history.py
│   ├── managers.py
│   ├── middleware.py
│   ├── migrations
│   │   ├── 0001_initial.py
│   │   ├── 0002_fix_str.py
│   │   ├── 0003_passwordexpiry_passwordhistory.py
│   │   ├── 0004_auto_20170416_1821.py
│   │   ├── 0005_update_default_language.py
│   │   └── __init__.py
│   ├── mixins.py
│   ├── models.py
│   ├── signals.py
│   ├── templatetags
│   │   ├── __init__.py
│   │   └── account_tags.py
│   ├── tests
│   │   ├── __init__.py
│   │   ├── settings.py
│   │   ├── test_auth.py
│   │   ├── test_commands.py
│   │   ├── test_decorators.py
│   │   ├── test_email_address.py
│   │   ├── test_models.py
│   │   ├── test_password.py
│   │   ├── test_views.py
│   │   └── urls.py
│   ├── timezones.py
│   ├── urls.py
│   ├── utils.py
│   └── views.py
├── django_user_accounts-3.3.1.dist-info
│   ├── LICENSE
│   ├── METADATA
│   ├── RECORD
│   ├── WHEEL
│   └── top_level.txt
├── docs
│   └── conf.py
├── makemigrations.py
├── manage.py
└── runtests.py

40 directories, 81 files
```

</details>

<details>
<summary>
Contents of sdist
</summary>

```
❯ tree dist/django-user-accounts-3.3.1
dist/django-user-accounts-3.3.1
├── CHANGELOG.md
├── LICENSE
├── MANIFEST.in
├── PKG-INFO
├── README.md
├── account
│   ├── __init__.py
│   ├── admin.py
│   ├── auth_backends.py
│   ├── conf.py
│   ├── context_processors.py
│   ├── decorators.py
│   ├── fields.py
│   ├── forms.py
│   ├── hooks.py
│   ├── languages.py
│   ├── locale
│   │   ├── ar
│   │   │   └── LC_MESSAGES
│   │   │       ├── django.mo
│   │   │       └── django.po
│   │   ├── de
│   │   │   └── LC_MESSAGES
│   │   │       ├── django.mo
│   │   │       └── django.po
│   │   ├── es
│   │   │   └── LC_MESSAGES
│   │   │       ├── django.mo
│   │   │       └── django.po
│   │   ├── fa_IR
│   │   │   └── LC_MESSAGES
│   │   │       ├── django.mo
│   │   │       └── django.po
│   │   ├── fr
│   │   │   └── LC_MESSAGES
│   │   │       ├── django.mo
│   │   │       └── django.po
│   │   ├── it
│   │   │   └── LC_MESSAGES
│   │   │       ├── django.mo
│   │   │       └── django.po
│   │   ├── ja
│   │   │   └── LC_MESSAGES
│   │   │       ├── django.mo
│   │   │       └── django.po
│   │   ├── nl
│   │   │   └── LC_MESSAGES
│   │   │       ├── django.mo
│   │   │       └── django.po
│   │   ├── pl
│   │   │   └── LC_MESSAGES
│   │   │       ├── django.mo
│   │   │       └── django.po
│   │   ├── pt_BR
│   │   │   └── LC_MESSAGES
│   │   │       ├── django.mo
│   │   │       └── django.po
│   │   ├── ru
│   │   │   └── LC_MESSAGES
│   │   │       ├── django.mo
│   │   │       └── django.po
│   │   ├── sk_SK
│   │   │   └── LC_MESSAGES
│   │   │       ├── django.mo
│   │   │       └── django.po
│   │   ├── tr
│   │   │   └── LC_MESSAGES
│   │   │       ├── django.mo
│   │   │       └── django.po
│   │   ├── zh_CN
│   │   │   └── LC_MESSAGES
│   │   │       ├── django.mo
│   │   │       └── django.po
│   │   └── zh_TW
│   │       └── LC_MESSAGES
│   │           ├── django.mo
│   │           └── django.po
│   ├── management
│   │   ├── __init__.py
│   │   └── commands
│   │       ├── __init__.py
│   │       ├── expunge_deleted.py
│   │       ├── user_password_expiry.py
│   │       └── user_password_history.py
│   ├── managers.py
│   ├── middleware.py
│   ├── migrations
│   │   ├── 0001_initial.py
│   │   ├── 0002_fix_str.py
│   │   ├── 0003_passwordexpiry_passwordhistory.py
│   │   ├── 0004_auto_20170416_1821.py
│   │   ├── 0005_update_default_language.py
│   │   └── __init__.py
│   ├── mixins.py
│   ├── models.py
│   ├── signals.py
│   ├── templatetags
│   │   ├── __init__.py
│   │   └── account_tags.py
│   ├── tests
│   │   ├── __init__.py
│   │   ├── settings.py
│   │   ├── templates
│   │   │   └── account
│   │   │       ├── email
│   │   │       │   ├── email_confirmation_message.txt
│   │   │       │   ├── email_confirmation_subject.txt
│   │   │       │   ├── password_change.txt
│   │   │       │   ├── password_change_subject.txt
│   │   │       │   ├── password_reset.txt
│   │   │       │   └── password_reset_subject.txt
│   │   │       ├── email_confirm.html
│   │   │       ├── email_confirmation_sent.html
│   │   │       ├── login.html
│   │   │       ├── logout.html
│   │   │       ├── password_change.html
│   │   │       ├── password_reset_sent.html
│   │   │       ├── password_reset_token.html
│   │   │       ├── password_reset_token_fail.html
│   │   │       ├── settings.html
│   │   │       ├── signup.html
│   │   │       └── signup_closed.html
│   │   ├── test_auth.py
│   │   ├── test_commands.py
│   │   ├── test_decorators.py
│   │   ├── test_email_address.py
│   │   ├── test_models.py
│   │   ├── test_password.py
│   │   ├── test_views.py
│   │   └── urls.py
│   ├── timezones.py
│   ├── urls.py
│   ├── utils.py
│   └── views.py
├── django_user_accounts.egg-info
│   └── SOURCES.txt
├── docs
│   ├── commands.rst
│   ├── conf.py
│   ├── faq.rst
│   ├── index.rst
│   ├── installation.rst
│   ├── migration.rst
│   ├── settings.rst
│   ├── signals.rst
│   ├── templates.rst
│   └── usage.rst
├── makemigrations.py
├── manage.py
├── pyproject.toml
├── runtests.py
└── setup.cfg

43 directories, 110 files
```

<details>

**Review by uhurusurfa — APPROVED** [review]
👍 Good to go

**Comment by blag** [comment]
@carchan1 Version 3.3.1 has been [available on PyPI](https://pypi.org/project/django-user-accounts/3.3.1/) since September 10th, 2023.

**Comment by carchan1** [comment]
@blag `0006_alter_signupcode_max_uses.py` [isn't included in 3.3.1 ](https://github.com/pinax/django-user-accounts/tree/v3.3.1/account/migrations) :/

**Comment by blag** [comment]
Oh, gotcha. Commenting in this PR made me think there was an issue with the 3.3.1 release, which was released before [the fix you are requesting](https://github.com/pinax/django-user-accounts/commit/8c7fe02f63993f8c2b6c1e315e1a2ab8de97b9fa).

The pre-release PR that will include the migrations you want is #378, but I won't be able to merge and push that release until next week.

**Pull request merged**
