### PR TITLE
Update changelog and bump version to 3.3.2

### PR DESCRIPTION
**Pull request by blag**
Changes proposed in this PR:

- Update changelog
- Bump version to 3.3.2 

I'd appreciate it if somebody independently verified that `account/migrations/0006_alter_signupcode_max_uses.py` and `account/migrations/0007_alter_emailconfirmation_sent.py` are both included in the built distribution (both wheel and sdist).

To check:

1. Clone this repo and `cd` to it.
2. Create and activate a virtualenv.
3. ```bash
   python3 -m pip install --upgrade build
   python3 -m build
   ```
4. Unzip the .whl in `dist/` and untar the tarball in `dist/` and check their contents include the mentioned migrations files.

**Tips for an ideal PR**
* You have read our Code of Conduct: https://github.com/pinax/.github/blob/master/CODE_OF_CONDUCT.md
* You have read our Contributing info: https://github.com/pinax/.github/blob/master/CONTRIBUTING.md
* The PR is atomic
* Unit tests have been updated/added, if needed
* App version number has been updated in `setup.py` (Pinax uses [SemVer](https://semver.org/))
* `Change Log` has been updated
* You have added your name to the `AUTHORS` file

### CODE REVIEW

**Comment by carchan1** [comment]
It works for me, both doing a `pip install` on the .whl and unzipping the .tar

**Comment by uhurusurfa** [comment]
@blag - you need to commit and push the migration file

**Comment by blag** [comment]
Isn't the migration file in question already in the `master` branch?

https://github.com/pinax/django-user-accounts/blob/master/account/migrations/0006_alter_signupcode_max_uses.py

I'm getting the feeling that I'm missing something obvious that I need to fix before merging this...

**Comment by uhurusurfa** [comment]
No - thats just me with amnesia 😵‍💫 
All good

**Review by uhurusurfa — APPROVED** [review]
💯

**Comment by carchan1** [comment]
Is it normal that 3.3.2 is't released yet?

**Comment by blag** [comment]
@carchan1 Thank you for your interest in the 3.3.2 release. Yes it is normal. We are still within the timeline I mentioned [here](https://github.com/pinax/django-user-accounts/pull/373#issuecomment-1739712700), and while reminders are nice once in awhile, they aren't positively productive when we are still within the communicated timeline. Also, don't be surprised if the expected timeline slips a bit.

This is an open source project, one of a few that I maintain, and I am not paid for any of the work I do. I am pulled in a thousand different directions at once and this project isn't necessarily my highest priority from moment to moment. If you would like to reduce the burden on us maintainers and make our jobs easier, it would be more helpful to contribute PRs for the fixes and improvements you wish to see, triage issues, and review the PRs of others. Or consider applying to become a maintainer yourself, which would allow you to independently commit changes and publish releases on your own.

**Comment by uhurusurfa** [comment]
We will inlcude an auto release mechanism as part of a github workflow soon that will lighten the burden of release maintenance but for now as @blag points out, it is not necessarily any of the current maintainers highest priority.

**Comment by blag** [comment]
Attempting to release now. If it goes well it should be out in a few minutes. If it doesn't go well it will need to wait until at least Monday.

**Comment by blag** [comment]
The release process went well. Thank you for your patience.

The v3.3.2 release is now available on [PyPI](https://pypi.org/project/django-user-accounts/3.3.2/) and [GitHub](https://github.com/pinax/django-user-accounts/releases/tag/v3.3.2).

In general, I'm not a huge fan of automated releases but if it eases the burden on maintainers then I'm willing to accept it. PRs implementing that are welcome and I'm happy to engage with testing that.

**Pull request merged**
