### PR TITLE
Require minimum password length

### PR DESCRIPTION
**Pull request by danjjl**
Default set to 8 characters.

### CODE REVIEW

**Comment by poulp** [comment]
+1

**Comment by beaugunderson** [comment]
What about `ChangePasswordForm` and `PasswordResetTokenForm`?

**Comment by stepmr** [comment]
+1

**Comment by ossanna16** [comment]
@brosner Can this be merged or is there a conflict?

**Comment by beaugunderson** [comment]
I don't think there's a conflict but the PR should be extended to the two other forms I mentioned first. :)

**Comment by ossanna16** [comment]
@beaugunderson Would you mind sending a PR including the extensions you mentioned? That would be awesome 😊

**Comment by beaugunderson** [comment]
@ossanna16 I've done so as PR #204; this PR can be closed in favor of that one. :sparkles:

**Comment by ossanna16** [comment]
👍

**Comment by beaugunderson** [comment]
@brosner feel free to close this PR as it's superseded by #204 ✨

**Pull request closed without merging**
